# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'QatarMuseumTicketingLib' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire', '~> 4.5'
  pod 'JGProgressHUD'
  pod 'SwiftyJSON'
  pod 'FSPagerView'
  pod 'Toast-Swift', '~> 4.0.0'
  pod 'ActionSheetPicker-3.0', '~> 2.3.0'
  pod 'Kingfisher', '<= 4.9.0'
  pod 'QRCode'
  pod 'KeychainSwift', '~> 11.0'

  # Pods for QatarMuseumTicketingLib

end
